# Generated by Django 2.0.5 on 2018-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.IntegerField(choices=[(0, 'sending'), (1, 'accepted'), (2, 'unfriend'), (3, 'blocked')], default=0),
        ),
    ]
